Adding ability to select both mongo 3.0 and 3.4 as an input
rs-services/server-templates pull request #54
Opened 2017-08-24 20:24 UTC by tusharshahrs

@rshade @gonzalez 
mongo replica set restore:
![tusharshah_upgrade-dev-productapi-mongo-01-34____ _-ssh_-l_tusharshah_ec2-34-198-51-71_compute-1_amazonaws_com_ _223x67](https://user-images.githubusercontent.com/5281839/29686591-912201d8-88e7-11e7-8e8f-e7329bf4e452.png)

mongo input on st:
![upgrade-dev-productapi-mongo-01-34_-_server_inputs](https://user-images.githubusercontent.com/5281839/29686725-1353733a-88e8-11e7-87b2-8dea3e24e7c6.png)

mongo backup:
![volume_snapshots](https://user-images.githubusercontent.com/5281839/29686828-65141558-88e8-11e7-94f7-3116c0708865.png)

2017-08-25 15:23 UTC, rshade approved these changes

2017-08-25 15:26 UTC, rshade requested changes

2017-08-25 15:26 UTC, rshade commented on mongodb/MongoDB_Install-chef.sh
> +
can you remove space here

2017-08-28 13:23 UTC, tusharshahrs commented on mongodb/MongoDB_Install-chef.sh
> +
Removed the extra space

2017-08-28 13:43 UTC, rshade approved these changes

2017-08-28 13:52 UTC, merged